import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    languageSidebar: [
        {
            type: 'category',
            label: 'Language',
            link: {
                type: 'generated-index',
            },
            items: [
                {type: 'autogenerated', dirName: '.'}
            ]
        }
    ]

};

export default sidebars;
